### ISSUE TITLE
[BACK]endpoint getUserByID

### ISSUE THREAD

**Issue by 8L312** [42LTeam/pong#110]
sur main quand utilise cet endpoint on a l'erreur :
Invalid `this.prisma.user.findUnique()` invocation in
/usr/src/app/src/user/user.service.ts:47:29

}

 async getUserById(id: number): Promise<User | null> {
   return this.prisma.user.findUnique({
          where: {
            id: 92488
          }
        })

 Argument `in`: Invalid value provided. Expected Int or ListIntFieldRefInput, provided (Int, String).
     at xn (/usr/src/app/node_modules/@prisma/client/runtime/library.js:116:5852)
     at vn.handleRequestError (/usr/src/app/node_modules/@prisma/client/runtime/library.js:123:6429)
     at vn.handleAndLogRequestError (/usr/src/app/node_modules/@prisma/client/runtime/library.js:123:6119)
     at vn.request (/usr/src/app/node_modules/@prisma/client/runtime/library.js:123:5839)
     at l (/usr/src/app/node_modules/@prisma/client/runtime/library.js:128:9763)

**Comment by 8L312** [comment]
L'erreur est peut-être liée à l'ajout de "UserIdValidationPipe" dans `user.controller.ts`

@Get(':id')
  @ApiOperation({ summary: 'Get user by id' })
  async getUserById(@Param('id', UserIdValidationPipe, ParseIntPipe) id: number): Promise<User | null> {
    return this.userService.getUserById(Number(id));
  }
  
  parce que si je le vire ça remarche normal 🤔
